BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK: []
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: https://cdn.sakura.vin/json/friends.json
  list:
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - "\u7B90\u6D1B\u5C9B"
    - https://www.shang.ac.cn
    - https://s1.ax1x.com/2023/08/03/pPiaXef.jpg
  - - Ether
    - http://blog.bywind.xyz
    - https://blog.bywind.xyz/img/avatar.png
  - - GanSer
    - https://www.gan1ser.top/
    - https://pic.imgdb.cn/item/63f16cddf144a010070697c8.jpg
  - - "\u9752\u7384\u535A\u5BA2"
    - http://blog.98to.cn
    - http://cdn.98to.cn/w34c0k.png
  - - "\u843D\u6587\u4E91\u5C4B"
    - https://www.52n.cc
    - https://www.52n.cc/favicon.ico
