# 友链页地址
# 参数说明：
# link：必填，在这里填写你的友链页面地址
# theme：必填，友链页的获取策略。需要指定该页面的主题，可选参数如下（这些是目前支持的主题）：
#   - common1: 通用主题1，请参考：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=友链页适配
#   - common2: 通用主题2，请参考：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=友链页适配
#   - butterfly：butterfly主题
#   - fluid：fluid主题
#   - matery：matery主题
#   - nexmoe：nexmoe主题
#   - stun：stun主题
#   - sakura: sakura主题
#   - volantis：volantis主题
#   - Yun：Yun主题
#   - stellar：stellar主题
# 支持配置多个友链页面并指定不同主题策略，每个用{}分隔，它们会被同时爬取，数据保存在一起。
LINK: [
#     { link: "https://www.yyyzyyyz.cn/link/", theme: "butterfly" },  # 友链页地址1，修改为你的友链页地址
#     { link: "https://noionion.top/link/", theme: "butterfly" }, # 友链页地址2
#     { link: "https://immmmm.com/about/", theme: "common1" }, # 友链页地址3
#     ...
]

# 配置项友链
# enable：# 是否启用配置项友链 true/false（针对还未适配主题或者有定制需求的用户）
# json_api：通过json格式配置友链，详见：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=配置项json友链
# list字段填写格式：["name", "link", "avatar","suffix"]，其中：
#       name：必填，友链的名字
#       link：必填，友链主页地址
#       avatar：必填，头像地址
#       suffix：选填，自定义订阅后缀，主要针对不规范的网站订阅后缀，见示例2
SETTINGS_FRIENDS_LINKS: {
    enable: true,
    json_api: "https://cdn.sakura.vin/json/friends.json",
    list: [
        # 示例1：
        ["贰猹の小窝", "https://noionion.top/", "https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg"],
        ["Akilarの糖果屋", "https://akilar.top/", "https://akilar.top/images/headimage.png"],
        ["安知鱼", "https://blog.anheyu.com/", "https://npm.elemecdn.com/anzhiyu-blog@1.1.6/img/post/common/anzhiy.cn.jpg"],
        ["Tianli", "https://tianli-blog.club/", "https://img02.anheyu.com/adminuploads/1/2022/11/11/636db0d451fd0.webp"],
        ["041专属个人主页", "https://www.lsy041.com", "https://lsy041.com/favicon.png"],
        ["Leonus", "https://blog.leonus.cn/", "https://q1.qlogo.cn/g?b=qq&nk=553344777&s=5"],
        ["云晓晨CatchWang", "https://www.catchwang.com", "https://cdn.catchwang.com/avatar.png"],
        ["剑客网", "https://www.go176.net/", "https://lsy041.com/favicon.png"],
        ["吃猫的鱼", "https://www.fish9.cn", "https://thirdqq.qlogo.cn/g?b=qq&nk=2911396166&s=100"],    
        ["小权的探险日记","https://www.nsxsb.com/", "https://p17.qhimg.com/t0106942689f1d0ca4a.png"], 
        ["小柒资源网", "https://www.17only.net/", "https://flower.cnnc404.com:8/images/35CB4418-8D36-4BA1-A856-1A15AFB783D8.jpg",], 
        ["张洪Heo", "https://blog.zhheo.com", "https://img.zhheo.com/i/2022/08/19/62ff32fa28da1.png"], 
        ["拾柒博客", "https://www.walsm.net", "https://q1.qlogo.cn/g?b=qq&nk=2676905526&s=100"], 
        ["月亮", "https://blog.monl.cc/", "https://image.muerg.cn/2/2023/07/16/64b383ff8b832.jpeg"], 
        ["杜老师说", "https://dusays.com/", "https://cdn.dusays.com/avatar.png"], 
        ["橙子源码", "https://www.cznote.cn", "https://cznote.cn/favicon.png"], 
        ["湘铭 `Blog", "https://blog.xiangming.site/", "https://photo.xiangming.site/img/icologo.png"], 
        ["满心记", "https://blog.lovelu.top/", "https://bu.dusays.com/2023/01/29/63d5bf7fa0d2c.png"], 
        ["知觉思墨", "https://mojuec.cn", "https://mojuec.cn/wp-content/uploads/2023/06/yuu.png"], 
        ["良生网", "https://www.zlsw.cc", "https://p.zlskj.top/lsbk/favicon48x48.png"], 
        ["轻笑Chuckle", "https://www.qcqx.cn", "https://www.qcqx.cn/img/head.webp"], 
        ["远方博客", "https://blog.ltyuanfang.cn", "https://tucdn.ltyuanfang.cn/images/2020/11/26/eebc2ac86abd7.jpg",], 
        ["阿里文案", "https://www.aliwenan.com", "https://oss.aliwenan.com/wp-content/uploads/2023/03/0f1a6bad3a4d6622167dd593969f1439.svg",], 
        ["顾熙博客", "https://blog.20021118.xyz/", "https://blog.20021118.xyz/wp-content/uploads/2023/07/logo.png",], 
        ["黎洛科技", "https://www.lho.cc", "https://q4.qlogo.cn/headimg_dl?dst_uin=277710066&spec=100",], 
        # 示例2：使用suffix的配置如下
        # 程序目前自动获取 "atom.xml", "feed/atom", "rss.xml", "rss2.xml", "feed", "index.xml" 这些后缀
        # 如果目标地址的后缀不在其中，就可以在这里添加
        # 比如 https://elizen.me/hello.xml ，填写：
        # ["elizen", "https://elizen.me/", "https://akilar.top/images/headimage.png", "hello.xml"]
    ]
}

# get links from gitee
# 从gitee issue中获取友链
GITEE_FRIENDS_LINKS: {
    enable: false, # true 开启gitee issue兼容
    type: "normal",  # volantis/stellar用户请在这里填写volantis
    owner:  "ccknbc",  # 填写你的gitee用户名
    repo:  "blogroll",  # 填写你的gitee仓库名
    state:  "open",  # 填写抓取的issue状态(open/closed)
}

# get links from github
# 从github issue中获取友链
GITHUB_FRIENDS_LINKS: {
    enable: false, # true 开启github issue兼容
    type: "normal",  # volantis/stellar用户请在这里填写volantis
    owner: "ccknbc",  # 填写你的github用户名
    repo: "ccknbc-actions",  # 填写你的github仓库名
    state: "open",  # 填写抓取的issue状态(open/closed)
    label: "active",  # 填写抓取的issue标签
}

# block site list
# 添加屏蔽站点，支持正则表达式
BLOCK_SITE: [
#    https://example.com/, # 屏蔽 https://example.com/
#    .*\.com,  # 含有.com的全部屏蔽
#    ^http://,  # http开头的全部屏蔽
]

# 每个友链最多获取几篇文章，此值越大，则抓取的文章上限越多，相应地运行速度也会降低，反之亦然
# 请设置一个正整数
MAX_POSTS_NUM: 5

# 启用HTTP代理，此项设为true，并且需要添加一个环境变量，名称为PROXY，值为[IP]:[端口]，比如：192.168.1.106:8080
HTTP_PROXY: false

# 过期文章清除（天）
OUTDATE_CLEAN: 60

# 5.x以后默认为sqlite，同时不建议使用leancloud
# 存储方式，可选项：leancloud，mysql，sqlite，mongodb；默认为sqlite
DATABASE: "sqlite"

# 部署方式，可选项：github，server，docker；默认为github
DEPLOY_TYPE: "github"
